name: Cypress Tests

on:
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [qalite-cypress-trigger]
  workflow_dispatch:

jobs:
  cypress-desktop:
    runs-on: ubuntu-latest
    outputs:
      pages_artifact: ${{ steps.upload-pages.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Cypress Desktop
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cy:run:desktop

      # ---------- ARTIFACTS ----------
      - name: Upload Videos (Desktop)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-desktop
          path: cypress/videos/
          retention-days: 7

      - name: Upload Screenshots (Desktop)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screens-desktop
          path: cypress/screenshots/

      # ---------- PAGES DESKTOP ----------
      - name: Prepare Desktop Videos for Pages
        if: always()
        run: |
          mkdir -p public/videos/desktop
          cp -r cypress/videos/* public/videos/desktop/

      - name: Upload Pages Artifact (Desktop)
        id: upload-pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: public


  cypress-mobile:
    runs-on: ubuntu-latest
    needs: cypress-desktop
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Cypress Mobile
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cy:run:mobile

      # ---------- ARTIFACTS ----------
      - name: Upload Videos (Mobile)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-mobile
          path: cypress/videos/
          retention-days: 7

      - name: Upload Screenshots (Mobile)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screens-mobile
          path: cypress/screenshots/

      # ---------- PAGES MOBILE ----------
      - name: Prepare Mobile Videos for Pages
        if: always()
        run: |
          mkdir -p public/videos/mobile
          cp -r cypress/videos/* public/videos/mobile/

      - name: Upload Pages Artifact (Mobile)
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: public


  # ---------- DEPLOY FINAL DO GITHUB PAGES ----------
  deploy-pages:
    runs-on: ubuntu-latest
    needs: [cypress-desktop, cypress-mobile]
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4