name: Cypress Test Suite

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Selecione a feature ou rode tudo'
        required: true
        type: choice
        options:
          - ALL
          - Login
          - Organization
          - Profile

      device:
        description: 'Selecione o dispositivo'
        required: true
        type: choice
        options:
          - desktop
          - mobile
          - ambos

  push:
    branches: [main]

  pull_request:
    branches: [main]

  repository_dispatch:
    types: [qalite-cypress-trigger]

jobs:
  desktop:
    if: >-
      github.event_name == 'repository_dispatch' ||
      inputs.device == 'desktop' ||
      inputs.device == 'ambos' ||
      github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint

      - name: Run Cypress Desktop
        uses: cypress-io/github-action@v6
        with:
          command: >
            ${{ inputs.feature == 'ALL'
                && format('npm run cy:run:all --environment=desktop')
                || format('npm run cy:run:feature --feature={0} --environment=desktop', inputs.feature)
            }}
          browser: chrome

  mobile:
    if: >-
      github.event_name == 'repository_dispatch' ||
      inputs.device == 'mobile' ||
      inputs.device == 'ambos' ||
      github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint

      - name: Run Cypress Mobile
        uses: cypress-io/github-action@v6
        with:
          command: >
            ${{ inputs.feature == 'ALL'
                && format('npm run cy:run:all --environment=mobile')
                || format('npm run cy:run:feature --feature={0} --environment=mobile', inputs.feature)
            }}
          browser: chrome
