name: Cypress Tests

on:
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [qalite-cypress-trigger]
  workflow_dispatch:

jobs:
  cypress-desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Cypress Desktop
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cy:run:desktop

  cypress-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Cypress Mobile
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run cy:run:mobile
