name: Cypress Test Suite

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Selecione a feature ou rode tudo'
        required: true
        type: choice
        options:
          - ALL
          - Login
          - Organization

      device:
        description: 'Selecione o dispositivo'
        required: true
        type: choice
        options:
          - desktop
          - mobile
          - ambos

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  desktop:
    if: ${{ (inputs.device == 'desktop' || inputs.device == 'ambos') || github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint

      - name: Run Cypress Desktop
        uses: cypress-io/github-action@v6
        with:
          command: >
            npm run cy:run --
            ${
              {# Seleção automática: se workflow_dispatch usa o input, caso contrário roda ALL #}
              github.event_name == 'workflow_dispatch'
              && (
                   inputs.feature != 'ALL'
                   && format('--spec cypress/e2e/features/{0}.feature', inputs.feature)
                   || ''
                 )
              || ''
            } --env environment=desktop
          browser: chrome
        env:
          QA_LITE_BASE_URL: ${{ secrets.QA_LITE_BASE_URL }}
          QA_LITE_AUTH_COOKIE: ${{ secrets.QA_LITE_AUTH_COOKIE }}

  mobile:
    if: ${{ (inputs.device == 'mobile' || inputs.device == 'ambos') || github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint

      - name: Run Cypress Mobile
        uses: cypress-io/github-action@v6
        with:
          command: >
            npm run cy:run --
            ${
              github.event_name == 'workflow_dispatch'
              && (
                   inputs.feature != 'ALL'
                   && format('--spec cypress/e2e/features/{0}.feature', inputs.feature)
                   || ''
                 )
              || ''
            } --env environment=mobile
          browser: chrome
        env:
          QA_LITE_BASE_URL: ${{ secrets.QA_LITE_BASE_URL }}
          QA_LITE_AUTH_COOKIE: ${{ secrets.QA_LITE_AUTH_COOKIE }}
